traj_server:
  ros__parameters:
    "traj_server/time_forward": 1.5
    "traj_server/pub_traj_id": 4
    "traj_server/init_x": 0.0
    "traj_server/init_y": 0.0
    "traj_server/init_z": 1.0
    "perception_utils/top_angle": 0.56125
    "perception_utils/left_angle": 0.69222
    "perception_utils/right_angle": 0.68901
    "perception_utils/max_dist": 4.5
    "perception_utils/vis_dist": 1.0
