<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>active_perception</name>
  <version>0.0.0</version>
  <description>The active_perception package</description>
  <maintainer email="boboyu@todo.todo">boboyu</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>pcl_conversions</depend>
  <depend>plan_env</depend>
  <depend>bspline</depend>
  <depend>path_searching</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
